### ISSUE TITLE
Terminal pwd is the path of the first project in tree-view when tree-view is active

### ISSUE THREAD

**Issue by tom-power** [Spiker985/x-terminal-reloaded#50]
### Prerequisites

* [ x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

When the tree-view is active and you open a new terminal, the terminal pwd is the path of first project in the tree-view, irrespective of which project the file selected is part of.  

I think the terminal pwd should be the path of the project that the selected file is in, this is the behavior when the file is selected in the editor.

### Steps to Reproduce

1. Open tree-view and add multiple project folders
2. Select a project or file within a project that is not the first project in tree-view
3. If selecting a file use keys, so the file doesn't become active in the editor view
4. Run x-terminal-reloaded:open

**Expected behavior:**

The terminal pwd should match the path of the selected project

**Actual behavior:**

The terminal pwd matches the path of the first project

**Reproduces how often:**

100%

### Versions

1.104.2023042014

**Comment by Spiker985** [comment]
Should be fixed in PR #51, release [v14.2.2](https://github.com/Spiker985/x-terminal-reloaded/releases/tag/v14.2.2)
