### ISSUE TITLE
updating to 14.2.6 from 14.2.1 fails on Arco Linux

### ISSUE THREAD

**Issue by EscherD** [Spiker985/x-terminal-reloaded#80]
[2023-09-26T17_26_42_421Z-debug.log](https://github.com/Spiker985/x-terminal-reloaded/files/12730385/2023-09-26T17_26_42_421Z-debug.log)

Not a clue as to what this means.  Hope you can help.  Thank you.

**Comment by tripplehelix** [comment]
Seems to be the same issue I had, python 3.11 doesn't work you need to switch to python 3.10 #79

**Comment by EscherD** [comment]
Thank you.

**Comment by Spiker985** [comment]
@EscherD Did reverting to 3.10 fix building for you? If so, I'll link it to the pinned issue for python

**Comment by EscherD** [comment]
I didn't try that. I looked into that but from what I read I gathered that it would cause me more problems than I wanted to deal with. I just started using the Atom Terminal package which works ok. Thank you for your help.

**Comment by Spiker985** [comment]
> I didn't try that. I looked into that but from what I read I gathered that it would cause me more problems than I wanted to deal with. I just started using the Atom Terminal package which works ok. Thank you for your help.
> […](#)
> On October 9, 2023 1:56:51 PM CDT, Spiker985 ***@***.***> wrote: @EscherD Did reverting to 3.10 fix building for you? If so, I'll link it to the pinned issue for python -- Reply to this email directly or view it on GitHub: [#80 (comment)](https://github.com/Spiker985/x-terminal-reloaded/issues/80#issuecomment-1753494868) You are receiving this because you were mentioned. Message ID: ***@***.***>

Thank you for your reply! Sorry this package wasn't as easy to use as I'd like. I'll go ahead and close this issue. Thanks!

**Comment by EscherD** [comment]
👍
